# Generated by Django 4.2.9 on 2025-02-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='tavern_option',
            field=models.BooleanField(default=False, help_text='Does the user plan to pay for food at the tavern?'),
        ),
    ]
