# Generated by Django 4.2.9 on 2025-02-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_tavern_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attending_build',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='event',
            name='max_monster_cores',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='event',
            name='traveling_attending_build',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
