# Generated by Django 4.2.9 on 2025-02-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_attending_build_event_max_monster_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
