# Generated by Django 4.2.9 on 2025-02-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_checkin_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
