# Generated by Django 4.2.9 on 2025-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='starting_affinity_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
