# Generated by Django 4.2.9 on 2025-01-25 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cultivator_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starting_build', models.PositiveIntegerField()),
                ('unspent_build', models.PositiveIntegerField()),
                ('unspent_affinity', models.PositiveIntegerField()),
                ('armor', models.PositiveIntegerField(default=0)),
                ('character_number', models.PositiveIntegerField(unique=True)),
                ('affinity_skills', models.ManyToManyField(blank=True, related_name='characters_with_affinity', to='cultivator_rules.affinityskill')),
                ('common_skills', models.ManyToManyField(blank=True, related_name='characters_with_common', to='cultivator_rules.commonskill')),
                ('cultivator_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.cultivatortier')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='cultivator_rules.race')),
                ('race_skills', models.ManyToManyField(blank=True, related_name='characters_with_race', to='cultivator_rules.raceskill')),
                ('starting_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_characters', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlottedCores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotted_affinity_total', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slotted_affinities', to='characters.characters')),
                ('cultivator_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivator_rules.cultivatortier')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraEssences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_essence', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_essences', to='characters.characters')),
                ('cultivator_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivator_rules.cultivatortier')),
            ],
        ),
        migrations.CreateModel(
            name='CharactersRacialSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_race_skills', to='characters.characters')),
                ('race_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivator_rules.raceskill')),
            ],
        ),
        migrations.CreateModel(
            name='CharactersAffinities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('affinity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_levels', to='cultivator_rules.affinity')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinity_levels', to='characters.characters')),
                ('cultivator_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.cultivatortier')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCommonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_common_skills', to='characters.characters')),
                ('common_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivator_rules.commonskill')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAffinitySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('affinity_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivator_rules.affinityskill')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_affinity_skills', to='characters.characters')),
                ('cultivator_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivator_rules.cultivatortier')),
            ],
        ),
    ]
