# Generated by Django 4.2.9 on 2025-02-01 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0003_characters_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='characters',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characters',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
