# Generated by Django 4.2.9 on 2025-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_characters_approval_status_characters_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
