# Generated by Django 4.2.9 on 2025-02-04 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_checkin_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cultivator_rules', '0001_initial'),
        ('characters', '0005_characters_approval_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterCoreSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('for_build', models.BooleanField(default=False)),
                ('for_affinity', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='characters.characters')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('teir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.cultivatortier')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('starting_build', models.PositiveIntegerField()),
                ('unspent_build', models.PositiveIntegerField()),
                ('unspent_affinity', models.PositiveIntegerField()),
                ('armor', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
                ('affinity_skills', models.ManyToManyField(blank=True, related_name='characters_with_affinity_history', to='cultivator_rules.affinityskill')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='characters.characters')),
                ('common_skills', models.ManyToManyField(blank=True, related_name='characters_with_common_history', to='cultivator_rules.commonskill')),
                ('cultivator_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.cultivatortier')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.race')),
                ('race_skills', models.ManyToManyField(blank=True, related_name='characters_with_race_history', to='cultivator_rules.raceskill')),
            ],
        ),
    ]
