# Generated by Django 4.2.9 on 2025-02-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_monstercorespent_characterhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='character_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
