# Generated by Django 4.2.9 on 2025-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_characters_character_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterhistory',
            name='total_build',
            field=models.PositiveIntegerField(default=46),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='total_build',
            field=models.PositiveIntegerField(default=46),
            preserve_default=False,
        ),
    ]
