# Generated by Django 4.2.9 on 2025-02-12 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivator_rules', '0001_initial'),
        ('characters', '0008_characterhistory_total_build_characters_total_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterhistory',
            name='affinities',
            field=models.ManyToManyField(related_name='characters_with_affinity_history', through='characters.CharactersAffinities', to='cultivator_rules.affinity'),
        ),
        migrations.AddField(
            model_name='characters',
            name='affinities',
            field=models.ManyToManyField(related_name='characters_with_affinity', through='characters.CharactersAffinities', to='cultivator_rules.affinity'),
        ),
        migrations.AddField(
            model_name='charactersaffinities',
            name='character_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affinity_levels', to='characters.characterhistory'),
        ),
        migrations.AlterField(
            model_name='charactersaffinities',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affinity_levels', to='characters.characters'),
        ),
    ]
