# Generated by Django 4.2.9 on 2025-02-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_alter_characters_affinity_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='total_affinity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
