# Generated by Django 4.2.9 on 2025-02-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TavernRegistration',
        ),
    ]
