# Generated by Django 4.2.9 on 2025-01-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Affinity',
                'verbose_name_plural': 'Affinities',
            },
        ),
        migrations.CreateModel(
            name='CultivatorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('build_low', models.PositiveIntegerField()),
                ('build_high', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Essence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_point', models.PositiveIntegerField(default=1)),
                ('max_extra_essence_per_tier', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('costume_requirements', models.TextField()),
                ('special_notes', models.TextField(blank=True)),
                ('starting_affinity_tier', models.PositiveIntegerField()),
                ('starting_affinity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_races', to='cultivator_rules.affinity')),
            ],
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('mental', 'Mental')], max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('build', models.PositiveIntegerField()),
                ('verbal', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.deliverymethod')),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.duration')),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.frequency')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cultivator_rules.race')),
            ],
        ),
        migrations.CreateModel(
            name='CommonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('build', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.duration')),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.frequency')),
                ('prereqs', models.ManyToManyField(blank=True, related_name='required_for', to='cultivator_rules.commonskill')),
            ],
        ),
        migrations.CreateModel(
            name='AffinitySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('build', models.PositiveIntegerField()),
                ('verbal', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('max_time_can_buy', models.PositiveIntegerField(default=1)),
                ('affinity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cultivator_rules.affinity')),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.deliverymethod')),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivator_rules.frequency')),
                ('prereqs', models.ManyToManyField(blank=True, related_name='required_for', to='cultivator_rules.affinityskill')),
            ],
        ),
    ]
